In [1]:
from google.colab import files

In [2]:
uploaded = files.upload()

Saving cleaned_df (1).xlsx to cleaned_df (1).xlsx


# **Import Libraries**

In [19]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split as TTS
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error
import pickle


In [5]:
df = pd.read_excel('cleaned_df (1).xlsx')

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2544 entries, 0 to 2543
Data columns (total 17 columns):
 #   Column                       Non-Null Count  Dtype 
---  ------                       --------------  ----- 
 0   pathrise_status              2544 non-null   object
 1   primary_track                2544 non-null   object
 2   cohort_tag                   2544 non-null   object
 3   program_duration_days        2544 non-null   int64 
 4   placed                       2544 non-null   int64 
 5   employment_status            2544 non-null   object
 6   highest_level_of_education   2544 non-null   object
 7   length_of_job_search         2544 non-null   object
 8   biggest_challenge_in_search  2544 non-null   object
 9   professional_experience      2544 non-null   object
 10  work_authorization_status    2544 non-null   object
 11  number_of_interviews         2544 non-null   int64 
 12  number_of_applications       2544 non-null   int64 
 13  gender                       2544

In [7]:
df.describe()

program_duration_days       placed  number_of_interviews  \
count            2544.000000  2544.000000           2544.000000   
mean              128.954403     0.375786              2.200472   
std               126.128256     0.484420              3.052803   
min                 0.000000     0.000000              0.000000   
25%                12.000000     0.000000              0.000000   
50%                97.000000     0.000000              1.000000   
75%               219.000000     1.000000              3.000000   
max               548.000000     1.000000             20.000000   

       number_of_applications  
count             2544.000000  
mean                36.500786  
std                 53.654896  
min                  0.000000  
25%                  9.000000  
50%                 20.000000  
75%                 45.000000  
max               1000.000000

# ***Feature Engineering***

* As regards, some columns are not necessary in this data frame, such as: id, cohort_tag, pathrise_status although, I removed the id at first, I will remove others from the dataframe.

In [8]:
clean_df =df.drop(columns= ['cohort_tag'], inplace=True)

In [9]:
x = df.drop(columns= ['placed'])

In [10]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
x = x.apply(le.fit_transform)

In [11]:
x

pathrise_status  primary_track  program_duration_days  \
0                   0              4                      0   
1                   0              3                      0   
2                   2              1                      0   
3                   2              3                      0   
4                   5              4                     89   
...               ...            ...                    ...   
2539                7              1                    373   
2540                7              0                    388   
2541                0              4                    388   
2542                0              4                    388   
2543                6              4                    277   

      employment_status  highest_level_of_education  length_of_job_search  \
0                     4                           0                     1   
1                     4                           5                     1   
2                     2                           4                     3   
3                     0                           0                     3   
4                     4                           0                     0   
...                 ...                         ...                   ...   
2539                  0                           4                     2   
2540                  0                           4                     1   
2541                  0                           0                     3   
2542                  0                           4                     3   
2543                  3                           4                     0   

      biggest_challenge_in_search  professional_experience  \
0                               5                        1   
1                               2                        0   
2                               1                        3   
3                               2                        3   
4                               5                        0   
...                           ...                      ...   
2539                            8                        2   
2540                            5                        0   
2541                            8                        0   
2542                            8                        0   
2543                            5                        0   

      work_authorization_status  number_of_interviews  number_of_applications  \
0                             0                     2                      39   
1                             1                     6                       0   
2                             1                     0                       0   
3                             1                     5                      13   
4                             3                    10                      23   
...                         ...                   ...                     ...   
2539                          1                     4                      11   
2540                          3                     1                       7   
2541                          1                     1                      14   
2542                          1                     2                      10   
2543                          4                     3                      20   

      gender  race  cohort_tag_month  cohort_tag_fortnight  
0          2     6                10                     0  
1          2     6                 4                     0  
2          2     2                 1                     1  
3          2     1                 1                     1  
4          2     2                 1                     0  
...      ...   ...               ...                   ...  
2539       2     6                 6                     0  
2540       2     6                 4                     1  
2541       1     6                11                     

In [12]:
x = df.drop(columns= ['placed'])

from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
x = x.apply(le.fit_transform)

In [13]:
x

pathrise_status  primary_track  program_duration_days  \
0                   0              4                      0   
1                   0              3                      0   
2                   2              1                      0   
3                   2              3                      0   
4                   5              4                     89   
...               ...            ...                    ...   
2539                7              1                    373   
2540                7              0                    388   
2541                0              4                    388   
2542                0              4                    388   
2543                6              4                    277   

      employment_status  highest_level_of_education  length_of_job_search  \
0                     4                           0                     1   
1                     4                           5                     1   
2                     2                           4                     3   
3                     0                           0                     3   
4                     4                           0                     0   
...                 ...                         ...                   ...   
2539                  0                           4                     2   
2540                  0                           4                     1   
2541                  0                           0                     3   
2542                  0                           4                     3   
2543                  3                           4                     0   

      biggest_challenge_in_search  professional_experience  \
0                               5                        1   
1                               2                        0   
2                               1                        3   
3                               2                        3   
4                               5                        0   
...                           ...                      ...   
2539                            8                        2   
2540                            5                        0   
2541                            8                        0   
2542                            8                        0   
2543                            5                        0   

      work_authorization_status  number_of_interviews  number_of_applications  \
0                             0                     2                      39   
1                             1                     6                       0   
2                             1                     0                       0   
3                             1                     5                      13   
4                             3                    10                      23   
...                         ...                   ...                     ...   
2539                          1                     4                      11   
2540                          3                     1                       7   
2541                          1                     1                      14   
2542                          1                     2                      10   
2543                          4                     3                      20   

      gender  race  cohort_tag_month  cohort_tag_fortnight  
0          2     6                10                     0  
1          2     6                 4                     0  
2          2     2                 1                     1  
3          2     1                 1                     1  
4          2     2                 1                     0  
...      ...   ...               ...                   ...  
2539       2     6                 6                     0  
2540       2     6                 4                     1  
2541       1     6                11                     

In [14]:
# Separate features (X) and target (y)
y = df['placed']
X =x

In [15]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state = 0)

from sklearn.linear_model import LogisticRegression
logreg = LogisticRegression()

In [16]:
logreg.fit(X_train,y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [17]:
prediction = logreg.predict(X_test)
prediction

array([0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0,
       0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0,
       0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1,
       0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0,

In [18]:
y_test

1691    0
480     0
1338    1
883     1
2451    0
       ..
547     0
2355    1
1926    0
2133    1
2073    1
Name: placed, Length: 509, dtype: int64

In [20]:
from sklearn.tree import DecisionTreeClassifier
DT = DecisionTreeClassifier(random_state=0, criterion= 'gini')
DT.fit(X_train, y_train)
pred = DT.predict(X_test)

In [21]:
from sklearn.metrics import confusion_matrix, f1_score, accuracy_score
print(accuracy_score(y_test, pred))
print(f1_score(y_test, pred))

1.0
1.0


In [22]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test,prediction)

array([[271,  58],
       [120,  60]])

In [23]:
y_test

1691    0
480     0
1338    1
883     1
2451    0
       ..
547     0
2355    1
1926    0
2133    1
2073    1
Name: placed, Length: 509, dtype: int64

In [24]:
X_test

pathrise_status  primary_track  program_duration_days  \
1691                6              4                     10   
480                 2              4                      0   
1338                5              4                    172   
883                 5              4                     83   
2451                0              0                    293   
...               ...            ...                    ...   
547                 8              3                     14   
2355                5              4                    196   
1926                6              3                      6   
2133                5              4                    325   
2073                5              4                    332   

      employment_status  highest_level_of_education  length_of_job_search  \
1691                  4                           4                     2   
480                   1                           4                     0   
1338                  3                           0                     1   
883                   3                           3                     3   
2451                  3                           4                     4   
...                 ...                         ...                   ...   
547                   4                           0                     0   
2355                  0                           0                     0   
1926                  3                           0                     3   
2133                  1                           4                     0   
2073                  4                           4                     1   

      biggest_challenge_in_search  professional_experience  \
1691                            5                        0   
480                             5                        0   
1338                            5                        3   
883                             8                        0   
2451                            3                        0   
...                           ...                      ...   
547                             5                        3   
2355                            2                        1   
1926                            6                        0   
2133                            5                        0   
2073                            8                        2   

      work_authorization_status  number_of_interviews  number_of_applications  \
1691                          1                     0                       6   
480                           3                     0                      10   
1338                          1                     1                      17   
883                           1                     4                      13   
2451                          3                     0                      22   
...                         ...                   ...                     ...   
547                           3                    10                      33   
2355                          1                     1                      25   
1926                          4                     1                      21   
2133                          3                     0                      15   
2073                          1                     1                      23   

      gender  race  cohort_tag_month  cohort_tag_fortnight  
1691       2     2                 0                     0  
480        2     7                 4                     0  
1338       2     2                 4                     0  
883        2     2                11                     2  
2451       2     1                10                     0  
...      ...   ...               ...                   ...  
547        1     2                 1                     2  
2355       2     6                 2                     0  
1926       2     2                10                     

In [25]:
len(y_test)

509

In [26]:
271+58+120+60

509

In [27]:
from sklearn.metrics import classification_report
print(classification_report(y_test,prediction))

              precision    recall  f1-score   support

           0       0.69      0.82      0.75       329
           1       0.51      0.33      0.40       180

    accuracy                           0.65       509
   macro avg       0.60      0.58      0.58       509
weighted avg       0.63      0.65      0.63       509



In [28]:
accuracy_score(y_test, prediction)

0.650294695481336

In [32]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier()
knn.fit(X_train,y_train)

KNeighborsClassifier()

In [34]:
prediction_knn = knn.predict(X_test)
prediction_knn

array([0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0,
       0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1,
       1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1,
       0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0,
       1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0,
       1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0,
       0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1,
       1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0,

In [35]:
y_test

1691    0
480     0
1338    1
883     1
2451    0
       ..
547     0
2355    1
1926    0
2133    1
2073    1
Name: placed, Length: 509, dtype: int64

In [36]:
confusion_matrix(y_test, prediction_knn)

array([[245,  84],
       [ 48, 132]])

In [37]:
accuracy_score(y_test, prediction_knn)

0.7406679764243614

In [38]:
print(classification_report(y_test, prediction_knn))

              precision    recall  f1-score   support

           0       0.84      0.74      0.79       329
           1       0.61      0.73      0.67       180

    accuracy                           0.74       509
   macro avg       0.72      0.74      0.73       509
weighted avg       0.76      0.74      0.74       509



# **Decision Tree classification algorithm**

In [39]:
from sklearn.tree import DecisionTreeClassifier


In [41]:
tree = DecisionTreeClassifier()
tree.fit(X_train , y_train)

DecisionTreeClassifier()

In [44]:
predict_tree = tree.predict(X_test)
predict_tree

array([0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0,
       0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1,
       0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0,
       1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0,
       1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0,

In [45]:
y_test

1691    0
480     0
1338    1
883     1
2451    0
       ..
547     0
2355    1
1926    0
2133    1
2073    1
Name: placed, Length: 509, dtype: int64

In [46]:
confusion_matrix(y_test,predict_tree)

array([[329,   0],
       [  0, 180]])

In [47]:
accuracy_score(y_test,predict_tree)

1.0

In [48]:
print(classification_report(y_test,predict_tree))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00       329
           1       1.00      1.00      1.00       180

    accuracy                           1.00       509
   macro avg       1.00      1.00      1.00       509
weighted avg       1.00      1.00      1.00       509



# **Random Forest classification algorithm**

In [49]:
from sklearn.ensemble import RandomForestClassifier

In [50]:
rf = RandomForestClassifier()

In [52]:
rf.fit(X_train,y_train)

RandomForestClassifier()

In [53]:
predict_rf = rf.predict(X_test)

In [55]:
predict_rf

array([0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0,
       0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1,
       0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0,
       1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0,
       1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0,

In [56]:
y_test

1691    0
480     0
1338    1
883     1
2451    0
       ..
547     0
2355    1
1926    0
2133    1
2073    1
Name: placed, Length: 509, dtype: int64

In [57]:
confusion_matrix(y_test,predict_rf)

array([[329,   0],
       [  1, 179]])

In [58]:
accuracy_score(y_test, predict_rf)

0.9980353634577603

In [59]:
print(classification_report(y_test, predict_rf))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00       329
           1       1.00      0.99      1.00       180

    accuracy                           1.00       509
   macro avg       1.00      1.00      1.00       509
weighted avg       1.00      1.00      1.00       509

